#!/usr/bin/env python3
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

STEP_NAME = "sync_backlog"
CODEBERG_API = "https://codeberg.org/api/v1"
CODEBERG_REPO = os.getenv("CODEBERG_REPO", "publicinformation/publicinformation-data")

SEVERITY_WEIGHT = {"error": 3, "warning": 2, "info": 1}

REQUIRED_LABELS = [
    {"name": "pipeline-issue", "color": "#0075ca"},
    {"name": "severity:error", "color": "#d73a4a"},
    {"name": "severity:warning", "color": "#e4e669"},
    {"name": "severity:info", "color": "#cfd3d7"},
    {"name": "priority:high", "color": "#b60205"},
    {"name": "priority:medium", "color": "#fbca04"},
    {"name": "priority:low", "color": "#0075ca"},
]


def make_key(step_name: str, issue: dict) -> str:
    raw = issue.get("error_type") or issue.get("description", "")
    slug = raw.lower().replace(" ", "_").replace("/", "_")[:40]
    return f"{step_name}:{slug}"


def _step_weight(step_name: str, pipeline_steps: list) -> float:
    n = len(pipeline_steps)
    if n <= 1:
        return 2.0
    idx = pipeline_steps.index(step_name) if step_name in pipeline_steps else 0
    return 2.0 - idx / (n - 1)


def score_issue(step_name: str, issue: dict, pipeline_steps: list) -> float:
    sw = SEVERITY_WEIGHT.get(issue.get("severity", "info"), 1)
    affected = issue.get("affected_count") or 0
    pw = _step_weight(step_name, pipeline_steps)
    return sw * affected * pw


def assign_priority_tiers(scored_items: list) -> list:
    if not scored_items:
        return []
    sorted_items = sorted(scored_items, key=lambda i: i["score"])
    n = len(sorted_items)
    result = []
    for idx, item in enumerate(sorted_items):
        if idx < n // 3:
            tier = "low"
        elif idx < (2 * n) // 3:
            tier = "medium"
        else:
            tier = "high"
        result.append({**item, "priority": tier})
    return result


def collect_issues(pipeline_dir: Path) -> tuple:
    """Returns (scored_dict, steps_with_eval).

    scored_dict: {pipeline-key: {key, step_name, issue, score, priority}}
    steps_with_eval: set of step names that had an issues.json file
    """
    config = json.loads((pipeline_dir / "pipeline.json").read_text())
    steps = config["steps"]

    raw = []
    steps_with_eval = set()

    for step_name in steps:
        issues_path = pipeline_dir / "steps" / step_name / "eval" / "issues.json"
        if not issues_path.exists():
            continue
        steps_with_eval.add(step_name)
        issues = json.loads(issues_path.read_text())
        for issue in issues:
            key = make_key(step_name, issue)
            raw.append({
                "key": key,
                "step_name": step_name,
                "issue": issue,
                "score": score_issue(step_name, issue, steps),
            })

    tiered = assign_priority_tiers(raw)
    scored_dict = {item["key"]: item for item in tiered}
    return scored_dict, steps_with_eval


def build_body(step_name: str, issue: dict, run_at: str) -> str:
    key = make_key(step_name, issue)
    affected = issue.get("affected_count", 0) or 0
    suggestion = issue.get("suggestion_detail", "") or ""
    return (
        f"**Affected:** {affected} records\n"
        f"**Step:** {step_name}\n"
        f"**Suggestion:** {suggestion}\n\n"
        f"_Auto-generated by sync_backlog. Last updated: {run_at}._\n\n"
        f"<!-- pipeline-key: {key} -->"
    )


def parse_pipeline_key(body: str) -> "str | None":
    if not body:
        return None
    m = re.search(r"<!-- pipeline-key: ([^\s>]+) -->", body)
    return m.group(1) if m else None
