#!/usr/bin/env python3
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests

STEP_NAME = "sync_backlog"
CODEBERG_API = "https://codeberg.org/api/v1"
CODEBERG_REPO = os.getenv("CODEBERG_REPO", "publicinformation/publicinformation-data")

SEVERITY_WEIGHT = {"error": 3, "warning": 2, "info": 1}

REQUIRED_LABELS = [
    {"name": "pipeline-issue", "color": "#0075ca"},
    {"name": "severity:error", "color": "#d73a4a"},
    {"name": "severity:warning", "color": "#e4e669"},
    {"name": "severity:info", "color": "#cfd3d7"},
    {"name": "priority:high", "color": "#b60205"},
    {"name": "priority:medium", "color": "#fbca04"},
    {"name": "priority:low", "color": "#0075ca"},
]


def make_key(step_name: str, issue: dict) -> str:
    raw = issue.get("error_type") or issue.get("description", "")
    slug = raw.lower().replace(" ", "_").replace("/", "_")[:40]
    return f"{step_name}:{slug}"


def _step_weight(step_name: str, pipeline_steps: list) -> float:
    n = len(pipeline_steps)
    if n <= 1:
        return 2.0
    idx = pipeline_steps.index(step_name) if step_name in pipeline_steps else 0
    return 2.0 - idx / (n - 1)


def score_issue(step_name: str, issue: dict, pipeline_steps: list) -> float:
    sw = SEVERITY_WEIGHT.get(issue.get("severity", "info"), 1)
    affected = issue.get("affected_count") or 0
    pw = _step_weight(step_name, pipeline_steps)
    return sw * affected * pw


def assign_priority_tiers(scored_items: list) -> list:
    if not scored_items:
        return []
    sorted_items = sorted(scored_items, key=lambda i: i["score"])
    n = len(sorted_items)
    result = []
    for idx, item in enumerate(sorted_items):
        if idx < n // 3:
            tier = "low"
        elif idx < (2 * n) // 3:
            tier = "medium"
        else:
            tier = "high"
        result.append({**item, "priority": tier})
    return result


def collect_issues(pipeline_dir: Path) -> tuple:
    """Returns (scored_dict, steps_with_eval).

    scored_dict: {pipeline-key: {key, step_name, issue, score, priority}}
    steps_with_eval: set of step names that had an issues.json file
    """
    config = json.loads((pipeline_dir / "pipeline.json").read_text())
    steps = config["steps"]

    raw = []
    steps_with_eval = set()

    for step_name in steps:
        issues_path = pipeline_dir / "steps" / step_name / "eval" / "issues.json"
        if not issues_path.exists():
            continue
        steps_with_eval.add(step_name)
        issues = json.loads(issues_path.read_text())
        for issue in issues:
            key = make_key(step_name, issue)
            raw.append({
                "key": key,
                "step_name": step_name,
                "issue": issue,
                "score": score_issue(step_name, issue, steps),
            })

    tiered = assign_priority_tiers(raw)
    scored_dict = {item["key"]: item for item in tiered}
    return scored_dict, steps_with_eval


def build_body(step_name: str, issue: dict, run_at: str) -> str:
    key = make_key(step_name, issue)
    affected = issue.get("affected_count", 0) or 0
    suggestion = issue.get("suggestion_detail", "") or ""
    return (
        f"**Affected:** {affected} records\n"
        f"**Step:** {step_name}\n"
        f"**Suggestion:** {suggestion}\n\n"
        f"_Auto-generated by sync_backlog. Last updated: {run_at}._\n\n"
        f"<!-- pipeline-key: {key} -->"
    )


def parse_pipeline_key(body: str) -> "str | None":
    if not body:
        return None
    m = re.search(r"<!-- pipeline-key: ([^\s>]+) -->", body)
    return m.group(1) if m else None


def ensure_labels(session: requests.Session, repo_api_url: str, steps_with_eval: set) -> dict:
    """Return name→id dict for all required labels, creating any that are missing."""
    resp = session.get(f"{repo_api_url}/labels", params={"limit": 200})
    resp.raise_for_status()
    existing = {l["name"]: l["id"] for l in resp.json()}

    step_labels = [
        {"name": f"step:{s}", "color": "#c5def5"}
        for s in steps_with_eval
    ]
    all_labels = REQUIRED_LABELS + step_labels
    label_ids = {}
    for label in all_labels:
        name = label["name"]
        if name in existing:
            label_ids[name] = existing[name]
        else:
            r = session.post(f"{repo_api_url}/labels", json=label)
            r.raise_for_status()
            label_ids[name] = r.json()["id"]
    return label_ids


def fetch_open_issues(session: requests.Session, repo_api_url: str) -> list:
    """Fetch all open issues labelled pipeline-issue, handling pagination."""
    issues = []
    page = 1
    while True:
        resp = session.get(
            f"{repo_api_url}/issues",
            params={"type": "issues", "state": "open", "labels": "pipeline-issue", "limit": 50, "page": page},
        )
        resp.raise_for_status()
        batch = resp.json()
        if not batch:
            break
        issues.extend(batch)
        if len(batch) < 50:
            break
        page += 1
    return issues


def _label_ids_for_item(item: dict, label_ids: dict) -> list:
    ids = [label_ids["pipeline-issue"]]
    severity_key = f"severity:{item['issue'].get('severity', 'info')}"
    if severity_key in label_ids:
        ids.append(label_ids[severity_key])
    priority_key = f"priority:{item['priority']}"
    if priority_key in label_ids:
        ids.append(label_ids[priority_key])
    step_key = f"step:{item['step_name']}"
    if step_key in label_ids:
        ids.append(label_ids[step_key])
    return ids


def _issue_needs_update(cb_issue: dict, item: dict, new_body: str) -> bool:
    existing_labels = {l["name"] for l in cb_issue.get("labels", [])}
    expected_labels = {
        "pipeline-issue",
        f"severity:{item['issue'].get('severity', 'info')}",
        f"priority:{item['priority']}",
        f"step:{item['step_name']}",
    }
    body_changed = _body_without_timestamp(cb_issue.get("body", "")) != _body_without_timestamp(new_body)
    labels_changed = existing_labels != expected_labels
    return body_changed or labels_changed


def _body_without_timestamp(body: str) -> str:
    return re.sub(r"Last updated: [^\n]+\.", "Last updated: <REDACTED>.", body or "")


def reconcile(
    session: requests.Session,
    repo_api_url: str,
    scored_dict: dict,
    open_issues: list,
    steps_with_eval: set,
    label_ids: dict,
    run_at: str,
) -> dict:
    result = {"created": 0, "updated": 0, "closed": 0, "skipped": 0, "run_at": run_at}

    codeberg_by_key = {}
    for issue in open_issues:
        key = parse_pipeline_key(issue.get("body", ""))
        if key:
            codeberg_by_key[key] = issue

    # CREATE issues that exist in eval but not in Codeberg
    for key, item in scored_dict.items():
        if key not in codeberg_by_key:
            title = f"[{item['step_name']}] {item['issue'].get('description', key)}"
            body = build_body(item["step_name"], item["issue"], run_at)
            ids = _label_ids_for_item(item, label_ids)
            resp = session.post(
                f"{repo_api_url}/issues",
                json={"title": title, "body": body, "labels": ids},
            )
            resp.raise_for_status()
            result["created"] += 1

    # UPDATE, SKIP, or CLOSE issues that exist in Codeberg
    for key, cb_issue in codeberg_by_key.items():
        if key in scored_dict:
            item = scored_dict[key]
            new_body = build_body(item["step_name"], item["issue"], run_at)
            if _issue_needs_update(cb_issue, item, new_body):
                ids = _label_ids_for_item(item, label_ids)
                resp = session.patch(
                    f"{repo_api_url}/issues/{cb_issue['number']}",
                    json={"body": new_body, "labels": ids},
                )
                resp.raise_for_status()
                result["updated"] += 1
            else:
                result["skipped"] += 1
        else:
            issue_step = key.split(":")[0]
            if issue_step in steps_with_eval:
                resp = session.patch(
                    f"{repo_api_url}/issues/{cb_issue['number']}",
                    json={"state": "closed"},
                )
                resp.raise_for_status()
                comment = session.post(
                    f"{repo_api_url}/issues/{cb_issue['number']}/comments",
                    json={"body": "Resolved: no longer detected by eval"},
                )
                comment.raise_for_status()
                result["closed"] += 1
            else:
                result["skipped"] += 1

    return result
