#!/usr/bin/env python3
import json
from pathlib import Path

import yaml

STEP_NAME = "sync_backlog"

SEVERITY_WEIGHT = {"error": 3, "warning": 2, "info": 1}


def make_key(step_name: str, issue: dict) -> str:
    raw = issue.get("error_type") or issue.get("description", "")
    slug = raw.lower().replace(" ", "_").replace("/", "_")[:40]
    return f"{step_name}:{slug}"


def _step_weight(step_name: str, pipeline_steps: list) -> float:
    n = len(pipeline_steps)
    if n <= 1:
        return 2.0
    idx = pipeline_steps.index(step_name) if step_name in pipeline_steps else 0
    return 2.0 - idx / (n - 1)


def score_issue(step_name: str, issue: dict, pipeline_steps: list) -> float:
    sw = SEVERITY_WEIGHT.get(issue.get("severity", "info"), 1)
    affected = issue.get("affected_count") or 0
    pw = _step_weight(step_name, pipeline_steps)
    return sw * affected * pw


def assign_priority_tiers(scored_items: list) -> list:
    if not scored_items:
        return []
    sorted_items = sorted(scored_items, key=lambda i: i["score"])
    n = len(sorted_items)
    result = []
    for idx, item in enumerate(sorted_items):
        if idx < n // 3:
            tier = "low"
        elif idx < (2 * n) // 3:
            tier = "medium"
        else:
            tier = "high"
        result.append({**item, "priority": tier})
    return result


def collect_issues(pipeline_dir: Path) -> tuple:
    """Returns (scored_dict, steps_with_eval).

    scored_dict: {pipeline-key: {key, step_name, issue, score, priority}}
    steps_with_eval: set of step names that had an issues.json file
    """
    config = json.loads((pipeline_dir / "pipeline.json").read_text())
    steps = config["steps"]

    raw = []
    steps_with_eval = set()

    for step_name in steps:
        issues_path = pipeline_dir / "steps" / step_name / "eval" / "issues.json"
        if not issues_path.exists():
            continue
        steps_with_eval.add(step_name)
        issues = json.loads(issues_path.read_text())
        for issue in issues:
            key = make_key(step_name, issue)
            raw.append({
                "key": key,
                "step_name": step_name,
                "issue": issue,
                "score": score_issue(step_name, issue, steps),
            })

    tiered = assign_priority_tiers(raw)
    scored_dict = {item["key"]: item for item in tiered}
    return scored_dict, steps_with_eval


def load_backlog(path: Path) -> list:
    """Load existing backlog.yml, returning list of issue dicts. Returns [] if file absent."""
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not data or "issues" not in data:
        return []
    return data["issues"]


def save_backlog(path: Path, issues: list, run_at: str) -> None:
    """Write issues list to backlog.yml with a last_updated header."""
    data = {
        "last_updated": run_at,
        "issues": issues,
    }
    header = "# Pipeline issue backlog — auto-generated by sync_backlog. Do not edit manually.\n"
    path.write_text(header + yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=False), encoding="utf-8")


def reconcile(
    scored_dict: dict,
    existing_issues: list,
    steps_with_eval: set,
    run_at: str,
) -> tuple:
    """Merge current scored issues with existing backlog.

    Returns (updated_issues, stats) where stats = {created, updated, resolved, unchanged}.
    """
    existing_by_key = {entry["key"]: entry for entry in existing_issues}
    stats = {"created": 0, "updated": 0, "resolved": 0, "unchanged": 0}
    result = []

    # Process current issues — create or update
    for key, item in scored_dict.items():
        issue = item["issue"]
        if key in existing_by_key:
            old = existing_by_key[key]
            changed = (
                old.get("affected_count") != (issue.get("affected_count") or 0)
                or old.get("priority") != item["priority"]
                or old.get("severity") != issue.get("severity", "info")
                or old.get("status") == "resolved"
            )
            if changed:
                result.append({
                    **old,
                    "description": issue.get("description", key),
                    "severity": issue.get("severity", "info"),
                    "priority": item["priority"],
                    "affected_count": issue.get("affected_count") or 0,
                    "suggestion_detail": issue.get("suggestion_detail", ""),
                    "status": "open",
                    "last_seen": run_at,
                })
                stats["updated"] += 1
            else:
                result.append({**old, "last_seen": run_at})
                stats["unchanged"] += 1
        else:
            result.append({
                "key": key,
                "step_name": item["step_name"],
                "description": issue.get("description", key),
                "severity": issue.get("severity", "info"),
                "priority": item["priority"],
                "affected_count": issue.get("affected_count") or 0,
                "suggestion_detail": issue.get("suggestion_detail", ""),
                "status": "open",
                "first_seen": run_at,
                "last_seen": run_at,
            })
            stats["created"] += 1

    # Carry forward issues not in current run
    for key, old in existing_by_key.items():
        if key in scored_dict:
            continue  # already handled above
        step_name = key.split(":")[0]
        if step_name not in steps_with_eval:
            result.append(old)
        elif old.get("status") == "resolved":
            result.append(old)
        else:
            result.append({**old, "status": "resolved", "resolved_at": run_at})
            stats["resolved"] += 1

    return result, stats
